export const SEED_DATA = [
  { category:'Networking/Connectivity', severity:'high', platforms:['Platform 1','Platform 2','Custom Build'],
    title:'No network connectivity after switch configuration',
    symptom:'All devices offline after Cisco 2960 initial setup. No pings between devices on any VLAN.',
    root_cause:'Native VLAN mismatch on trunk port between PFSense and Cisco 2960. Port G1/0/24 not configured as trunk.',
    steps:['Verify trunk port config: show interfaces G1/0/24 trunk','Confirm native VLAN matches PFSense WAN VLAN','Run: switchport mode trunk on G1/0/24','Set allowed VLANs: switchport trunk allowed vlan 1,850','Verify PFSense LAN interface is bound to correct VLAN','Ping test from SmartBox to HUB Server after changes'],
    resolution:'Trunk port G1/0/24 misconfigured — set to access mode instead of trunk. Reconfigured as trunk with VLANs 1 and 850 allowed. Full connectivity restored.', submitted_by:'Worldvue Team' },
  { category:'VLAN', severity:'high', platforms:['Platform 1','Platform 2'],
    title:'VLAN 850 content not passing through core switch',
    symptom:'SmartBox and HUB Server online but STBs not receiving channel lineup. VLAN 850 traffic not forwarding.',
    root_cause:'VLAN 850 not created on switch or not added to trunk. Content VLAN must be explicitly allowed.',
    steps:['Check VLAN exists: show vlan brief — look for VLAN 850','If missing: vlan 850 / name CONTENT','Verify G1/0/1 VLAN 850 uplink: show run interface G1/0/1','Confirm SmartBox Data 2 on G1/0/2 is in VLAN 850','Check HUB Server Port 2 on G1/0/3 — access VLAN 850','Re-test STB channel load after VLAN corrections'],
    resolution:'VLAN 850 was not created on the switch. Created VLAN, assigned correct ports, content traffic restored within 2 minutes.', submitted_by:'Worldvue Team' },
  { category:'FTG', severity:'high', platforms:['Platform 1','Platform 2'],
    title:'TVs not receiving FTG channel lineup from HUB Server',
    symptom:'LG TVs powered on but showing no channels. FTG mode active but lineup empty.',
    root_cause:'HUB Server management port (Port 3) not reachable on management VLAN. TVs cannot pull config from HUB.',
    steps:['Ping HUB Server management IP from laptop on VLAN 1','Verify Port 3 → G1/0/22 connection and link light','Check G1/0/22 access VLAN: show run interface G1/0/22','Confirm HUB Server management IP is in correct subnet','Reboot HUB Server if IP config confirmed correct','Re-run TV FTG clone from HUB Server admin panel'],
    resolution:'Port G1/0/22 was in wrong access VLAN. Corrected to management VLAN 1. HUB Server became reachable and FTG lineup pushed successfully.', submitted_by:'Worldvue Team' },
  { category:'OTT', severity:'high', platforms:['Platform 1','Platform 2','Custom Build'],
    title:'OTT apps not loading — content port blocked',
    symptom:'FTG channels work fine but OTT streaming apps fail to load or buffer constantly.',
    root_cause:'Content VLAN 850 uplink to ISP (G1/0/1) has incorrect port assignment or VLAN tag stripped at PFSense.',
    steps:['Verify PFSense VLAN 850 interface is active and has WAN route','Check G1/0/1 VLAN 850 tag passing: show interfaces G1/0/1 trunk','Test internet connectivity from a device on VLAN 850','Check PFSense firewall rules — OTT traffic may be blocked','Verify DNS resolves correctly on VLAN 850 clients','Check SmartBox Data 2 / HUB Port 2 content path end-to-end'],
    resolution:'PFSense VLAN 850 interface had no default gateway set. Added correct ISP gateway. OTT streaming restored on all room STBs.', submitted_by:'Worldvue Team' },
  { category:'Native Casting', severity:'medium', platforms:['Platform 1','Platform 2','Custom Build'],
    title:'World Cinema Chromecast (WCC) not discoverable by guest devices',
    symptom:'Guests cannot find Chromecast device on hotel WiFi. Cast icon not appearing in apps.',
    root_cause:'mDNS not bridged between guest WiFi VLAN and WCC VLAN. Chromecast discovery relies on mDNS multicast.',
    steps:['Confirm WCC is on correct VLAN per topology','Check PFSense mDNS repeater / Avahi is installed and running','Verify mDNS is configured to bridge guest WiFi VLAN to WCC VLAN','Test discovery from guest WiFi — cast icon should appear in 60s','If still failing, check WCC firmware is current','Factory reset WCC if firmware confirmed and mDNS confirmed OK'],
    resolution:'PFSense Avahi mDNS repeater was not bridging the correct VLANs. Updated interface list in Avahi config. Chromecast became discoverable within 60 seconds.', submitted_by:'Worldvue Team' },
  { category:'Hardware', severity:'medium', platforms:['Platform 1','Platform 2'],
    title:'SmartBox not obtaining DHCP address on management VLAN',
    symptom:'SmartBox Data 1 plugged into G1/0/23 but device shows no IP. Cannot reach SmartBox admin page.',
    root_cause:'G1/0/23 configured in wrong VLAN or DHCP scope exhausted on management VLAN.',
    steps:['Check G1/0/23 config: show run interface G1/0/23','Confirm access VLAN is management VLAN (usually 1)','Check DHCP server has available leases on management subnet','Verify SmartBox Data 1 cable is in correct port (not Data 2)','Try static IP on SmartBox to isolate DHCP vs port issue','Check for duplicate IP if static works but DHCP fails'],
    resolution:'G1/0/23 was set to VLAN 850 instead of management VLAN. Corrected port VLAN. SmartBox obtained DHCP lease immediately.', submitted_by:'Worldvue Team' },
  { category:'VLAN', severity:'medium', platforms:['Custom Build'],
    title:'CMTS GIGE port not tagged on content VLAN',
    symptom:'CMTS control port reachable but coax distribution not working. STBs not getting OTT over coax.',
    root_cause:'CMTS GIGE port requires VLAN 850 tag. Port G1/0/2 must be access port in VLAN 850.',
    steps:['Verify CMTS GIGE port connected to G1/0/2','Show G1/0/2 config: show run interface G1/0/2','Set access VLAN 850: switchport access vlan 850','Confirm CMTS control port → G1/0/21 on management VLAN','Reboot CMTS after VLAN correction','Test coax STB after CMTS restart (~3 min)'],
    resolution:'G1/0/2 was in default VLAN 1 instead of 850. Corrected access VLAN. CMTS began distributing OTT over coax within 3 minutes of restart.', submitted_by:'Worldvue Team' },
  { category:'FTG', severity:'low', platforms:['Platform 2'],
    title:'LG Pro:Centric Server PCS400 not pushing channel map',
    symptom:'Pro:Centric server reachable but TVs not downloading channel map. TVs show generic menu.',
    root_cause:'Pro:Centric server management port (Port 3) on wrong switch port. Must be on G1/0/20 or G1/0/21 depending on CMTS presence.',
    steps:['Determine if CMTS is present in topology','With CMTS: Pro:Centric management → G1/0/20; Without: → G1/0/21','Verify cable in correct port with link light','Ping Pro:Centric management IP from management VLAN','Access Pro:Centric web admin and confirm channel map is published','Reboot TVs to force Pro:Centric re-download'],
    resolution:'Pro:Centric management port was on G1/0/22 (reserved for HUB Server). Moved to G1/0/21. Channel map downloaded to all TVs within 5 minutes.', submitted_by:'Worldvue Team' },
  { category:'Networking/Connectivity', severity:'medium', platforms:['Platform 1','Platform 2'],
    title:'PFSense WAN port not connecting to ISP — wrong port assignment',
    symptom:'PFSense shows WAN link down. No internet access for any device on the network.',
    root_cause:'PFSense Port 1 connected to wrong LSP core switch port. Must match topology WAN port assignment exactly.',
    steps:['Confirm topology WAN port assignment for this site','Check physical cable from PFSense Port 1 to LSP switch','Verify correct port number on LSP side matches topology doc','Check LSP switch port is active and not in error-disabled state','If port ok, check PFSense WAN interface config — correct IP/gateway?','Test with laptop plugged directly into LSP port to confirm ISP feed'],
    resolution:'PFSense was plugged into G1/0/4 instead of the specified WAN port in the topology. Moved cable to correct port. WAN came up immediately.', submitted_by:'Worldvue Team' },
  { category:'OTT', severity:'high', platforms:['Platform 1','Custom Build'],
    title:'4K Blonder Tongue encoder not reachable for management',
    symptom:'4K encoder shows link but cannot access web management UI. Cannot configure channel encoding.',
    root_cause:'Encoder remote control port on wrong switch port. Without CMTS: G1/0/21. With CMTS: G1/0/20.',
    steps:['Identify if CMTS is in this topology','Without CMTS: encoder remote control port → G1/0/21','With CMTS: encoder remote control port → G1/0/20','Verify cable seated in correct switch port','Ping encoder management IP from management VLAN laptop','Access encoder web UI at its management IP'],
    resolution:'Encoder was wired to G1/0/22 (HUB Server port). Moved remote control port to G1/0/21 per topology standard. Encoder management UI accessible immediately.', submitted_by:'Worldvue Team' },
  { category:'Native Casting', severity:'low', platforms:['Platform 1','Platform 2','Custom Build'],
    title:'Guest device connected to WiFi but casting fails mid-session',
    symptom:'Casting starts successfully but drops after 30-60 seconds. Reconnecting works briefly then drops again.',
    root_cause:'WiFi AP client isolation enabled — blocks peer-to-peer communication needed for casting control.',
    steps:['Access WiFi AP admin panel','Locate client isolation / AP isolation setting','Disable client isolation on guest casting SSID','Save and apply — no reboot needed on most APs','Test cast session — should maintain stable connection','Monitor for 5 minutes to confirm no more drops'],
    resolution:'Client isolation was enabled on the guest WiFi SSID. Disabled it. Casting sessions became stable and no longer dropped.', submitted_by:'Worldvue Team' },
  { category:'Hardware', severity:'high', platforms:['Platform 1','Platform 2','Custom Build'],
    title:'Cisco 2960 port in err-disabled state — no link recovery',
    symptom:'Switch port shows err-disabled in show interfaces. Device plugged into that port is completely offline.',
    root_cause:'Port shut down by switch due to BPDU guard violation (device sent STP BPDUs) or security violation.',
    steps:['Identify affected port: show interfaces status | include err','Check reason: show interfaces G1/0/X','If BPDU guard: ensure correct device is plugged in (not another switch)','Recover port: interface G1/0/X / shutdown / no shutdown','If recurring, add: spanning-tree portfast on the port','If security violation: check for unauthorized device on port'],
    resolution:'BPDU guard triggered because a small unmanaged switch was plugged in by hotel staff. Removed the device, re-enabled port, added portfast. No further violations.', submitted_by:'Worldvue Team' },
]
